Repository cse110-fa21-group17/cse110-fa21-group17, pull requests merged in 2021-11, with the labels that each got.

#6 Create 110421-Fifth Group Meeting.md
  admin/meetings/110421-Fifth Group Meeting.md
Labels: documentation

#7 Boiler plate and db
  app/.env_sample
  app/.gitignore
  app/Dockerfile
  app/app.js
  app/bin/www
  app/database/dbConfig.js
  app/database/migrations/20211109062017_users.js
  app/database/migrations/20211109062709_saved_recipes.js
  app/database/migrations/20211109063000_recipes.js
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/public/stylesheets/style.css
  app/routes/index.js
  app/routes/users.js
  app/views/error.ejs
  app/views/index.ejs
  docker-compose.yml
Labels: enhancement

#9 feat: added functions for insert/get from users table
  app/database/models/usersModel.js
Labels: enhancement

#19 cicd phase 1 documentation
  admin/cipipeline/phase1.md
Labels: documentation

#21 Eslint + super linter config
  .github/workflows/linter.yml
  app/.eslintrc.json
  app/package-lock.json
  app/package.json
Labels: bug, enhancement

#33 add sprint 1 retrospective
  admin/meetings/111521-retrospective.md
Labels: documentation

#34 Password match utility
  admin/meetings/SeventhStandupMeeting.md
  app/package-lock.json
  app/public/javascripts/passValid.js
  app/routes/index.js
  app/views/pages/signup.ejs
Labels: enhancement

#32 added token utility
  app/.env_sample
  app/app.js
  app/auth/token.js
  app/middlewares/verifyCookieToken.js
  app/package-lock.json
  app/package.json
  app/routes/index.js
Labels: enhancement

#36 new recipe backend connection
  app/app.js
  app/database/models/recipesModel.js
  app/middlewares/verifyCookieToken.js
  app/routes/dashboard.js
  app/views/pages/AddRecipeSuccess.ejs
  app/views/pages/newrecipe.ejs
Labels: enhancement

#39 Landing page
  app/routes/index.js
  app/views/index.ejs
Labels: enhancement, Discussion needed (severe)

#50 Add codacy badge and code doc page to Readme
  README.md
  app/public/javascripts/timer.js
Labels: documentation, enhancement
